language: php

php:
  - 7.1

install:
  - composer global require drupal/coder >2
  - composer global require drupal/coder 8.*

script:
  - ~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml -v .
